workloads:
  cpu_intensive:
    - name: "sysbench_cpu"
      command: "sysbench --test=cpu --cpu-max-prime=20000 run"
      duration: 180
    - name: "stress_cpu"
      command: "stress -c 4 -t 300"
      duration: 300
  
  memory_intensive:
    - name: "sysbench_memory"
      command: "sysbench --test=memory --memory-block-size=1K --memory-total-size=10G run"
      duration: 240
    - name: "stress_memory"
      command: "stress --vm 2 --vm-bytes 1G --vm-keep -t 300"
      duration: 300
  
  io_intensive:
    - name: "sysbench_fileio"
      command: "sysbench --test=fileio --file-test-mode=rndrw run"
      duration: 180
    - name: "dd_test"
      command: "dd if=/dev/zero of=test.img bs=1G count=2 oflag=dsync"
      duration: 120
  
  mixed_workloads:
    - name: "mixed_1"
      commands:
        - "stress -c 2 -t 300"
        - "stress --vm 1 --vm-bytes 512M --vm-keep -t 300"
      duration: 300
    - name: "mixed_2"
      commands:
        - "sysbench --test=cpu --cpu-max-prime=10000 run"
        - "dd if=/dev/zero of=test2.img bs=100M count=5 oflag=dsync"
      duration: 180

sequences:
  phase_transition_1:
    - workload: "cpu_intensive.sysbench_cpu"
      duration: 120
    - workload: "memory_intensive.sysbench_memory" 
      duration: 120
    - workload: "io_intensive.sysbench_fileio"
      duration: 120
  
  competing_vms:
    - workload: "cpu_intensive.stress_cpu"
      target_vms: [1, 2]
      duration: 180
    - workload: "memory_intensive.stress_memory"
      target_vms: [3, 4]
      duration: 180
